Conditional  with loc and iloc

In [73]:
#Conditional with loc 
import pandas as pd

Df = pd.DataFrame({
    "name":   ["Alice", "Bob", "Carol", "David" , "Bob"],
    "city":   ["New York", "Chicago", "Houston", "Seattle" , "Chicago"],
    "salary": [85000, 72000, 91000, 67000 , 72000]
}, index=[10, 20, 30, 40 , 50]) 

# Conditional selection using loc

Df.loc[(Df["salary"] > 70000) & (Df["salary"] < 90000)]

# OR → at least one must be true
Df.loc[(Df["city"] == "Chicago") | (Df["city"] == "Seattle")]

# NOT → negate a condition
Df.loc[~(Df["city"] == "New York")]

#Condition + select specific column

# salary of employees in Seattle only
Df.loc[Df["city"] == "Seattle", "salary"]

# name and salary where salary > 80000
Df.loc[Df["salary"] > 80000, ["name", "salary"]]


# Condition + update values

# give a raise to employees earning less than 75000
Df.loc[Df["salary"] < 75000, "salary"] += 5000

# update city for a specific name
Df.loc[Df["name"] == "Bob", "city"] = "New York"

Filtering based on String using loc

In [2]:
import pandas as pd

dict = {
    "name":       ["Alice Johnson", "Bob Smith", "Carol Davis", "David Lee", "Eva Martinez"],
    "city":       ["New York", "Los Angeles", "Chicago", "Houston", "Seattle"],
    "department": ["Engineering", "Marketing", "Finance", "HR", "Engineering"],
    "salary":     [85000, 72000, 91000, 67000, 95000]
}

df = pd.DataFrame(dict)
df

            name         city   department  salary
0  Alice Johnson     New York  Engineering   85000
1      Bob Smith  Los Angeles    Marketing   72000
2    Carol Davis      Chicago      Finance   91000
3      David Lee      Houston           HR   67000
4   Eva Martinez      Seattle  Engineering   95000

In [4]:
df.loc[df['city'].str.contains('New')] # return all the row where city - New

df.loc[df['city'].str.contains("new" , case = False)]

            name      city   department  salary
0  Alice Johnson  New York  Engineering   85000

In [5]:
#starts with los 
df.loc[df['city'].str.contains(r"^Los" )]

        name         city department  salary
1  Bob Smith  Los Angeles  Marketing   72000

In [6]:
# ends with 
df.loc[df['name'].str.contains(r"on$")]

            name      city   department  salary
0  Alice Johnson  New York  Engineering   85000

In [7]:
# starts with vowel 
df.loc[df["name"].str.contains(r"^[AEIOUaeiou]")]

            name      city   department  salary
0  Alice Johnson  New York  Engineering   85000
4   Eva Martinez   Seattle  Engineering   95000

In [8]:
#
df.loc[df["city"].str.contains(r"New|Los|Chicago")]

            name         city   department  salary
0  Alice Johnson     New York  Engineering   85000
1      Bob Smith  Los Angeles    Marketing   72000
2    Carol Davis      Chicago      Finance   91000

Adding new Column and Saving the file

In [3]:
df=pd.read_csv('./students_marks.csv')
df

    Roll              Name  Math  Physics  English Section
0      1     Alice Johnson    85       78     92.0       A
1      2         Bob Smith    72       88     65.0       B
2      3       Carol White    90       95      NaN       B
3      4       David Brown    55       60     70.0       A
4      5        Emma Davis    78       82     85.0       B
5      6      Frank Miller    63       57     74.0       A
6      7      Grace Wilson    91       89     93.0       B
7      8       Henry Moore    48       52     61.0       A
8      9   Isabella Taylor    76       79      NaN       B
9     10    James Anderson    83       75     87.0       A
10    11      Karen Thomas    69       71     68.0       B
11    12      Liam Jackson    95       92     90.0       A
12    13        Mia Harris    57       63     72.0       B
13    14       Noah Martin    80       77     83.0       A
14    15     Olivia Garcia    85       78      NaN       B
15    16     Paul Martinez    61       66     59.0       A
16    17    Quinn Robinson    88       91     86.0       B
17    18      Rachel Clark    53       49     64.0       A
18    19  Samuel Rodriguez    77       78     80.0       B
19    20               NaN    92       88     94.0       A

In [ ]:
df["Country"] = "Bangladesh"
df

In [11]:
df["Total Marks"] =df["Math"]+df["English"] +df["Physics"]
df

    Roll              Name  Math  Physics  English     Country  Total Marks
0      1     Alice Johnson    85     78.0     92.0  Bangladesh        255.0
1      2         Bob Smith    72     88.0     65.0  Bangladesh        225.0
2      3       Carol White    90     95.0      NaN  Bangladesh          NaN
3      4       David Brown    55     60.0     70.0  Bangladesh        185.0
4      5        Emma Davis    78     82.0     85.0  Bangladesh        245.0
5      6      Frank Miller    63     57.0     74.0  Bangladesh        194.0
6      7      Grace Wilson    91     89.0     93.0  Bangladesh        273.0
7      8       Henry Moore    48     52.0     61.0  Bangladesh        161.0
8      9   Isabella Taylor    76     79.0      NaN  Bangladesh          NaN
9     10    James Anderson    83     75.0     87.0  Bangladesh        245.0
10    11      Karen Thomas    69     71.0     68.0  Bangladesh        208.0
11    12      Liam Jackson    95     92.0     90.0  Bangladesh        277.0
12    13        Mia Harris    57     63.0     72.0  Bangladesh        192.0
13    14       Noah Martin    80     77.0     83.0  Bangladesh        240.0
14    15     Olivia Garcia    85     78.0      NaN  Bangladesh          NaN
15    16     Paul Martinez    61     66.0     59.0  Bangladesh        186.0
16    17    Quinn Robinson    88     91.0     86.0  Bangladesh        265.0
17    18      Rachel Clark    53     49.0     64.0  Bangladesh        166.0
18    19  Samuel Rodriguez    77      NaN     80.0  Bangladesh          NaN
19    20        Tina Lewis    92     88.0     94.0  Bangladesh        274.0

In [12]:
import numpy as np

df["Grade"]= np.where(df["Total Marks"] >=270 , "A+" , "A")
df

,Roll,Name,Math,Physics,English,Country,Total Marks,Grade
0,1,Alice Johnson,85,78.0,92.0,Bangladesh,255.0,A
1,2,Bob Smith,72,88.0,65.0,Bangladesh,225.0,A
2,3,Carol White,90,95.0,NaN,Bangladesh,NaN,A
3,4,David Brown,55,60.0,70.0,Bangladesh,185.0,A
4,5,Emma Davis,78,82.0,85.0,Bangladesh,245.0,A
5,6,Frank Miller,63,57.0,74.0,Bangladesh,194.0,A
6,7,Grace Wilson,91,89.0,93.0,Bangladesh,273.0,A+
7,8,Henry Moore,48,52.0,61.0,Bangladesh,161.0,A
8,9,Isabella Taylor,76,79.0,NaN,Bangladesh,NaN,A
9,10,James Anderson,83,75.0,87.0,Bangladesh,245.0,A
10,11,Karen Thomas,69,71.0,68.0,Bangladesh,208.0,A
11,12,Liam Jackson,95,92.0,90.0,Bangladesh,277.0,A+
12,13,Mia Harris,57,63.0,72.0,Bangladesh,192.0,A
13,14,Noah Martin,80,77.0,83.0,Bangladesh,240.0,A
14,15,Olivia Garcia,85,78.0,NaN,Bangladesh,NaN,A
15,16,Paul Martinez,61,66.0,59.0,Bangladesh,186.0,A
16,17,Quinn Robinson,88,91.0,86.0,Bangladesh,265.0,A
17,18,Rachel Clark,53,49.0,64.0,Bangladesh,166.0,A
18,19,Samuel Rodriguez,77,NaN,80.0,Bangladesh,NaN,A
19,20,Tina Lewis,92,88.0,94.0,Bangladesh,274.0,A+

In [ ]:
df["Passed in Math"]=df["Math"]>60
df

In [ ]:
df.drop(columns=["Passed in Math"])
df

In [ ]:
df=df.drop(columns=["Country" , "Passed in Math"])
df

In [16]:
df["First name"]=df["Name"].str.split(' ').str[0]  # split the name by space and take the first part
df

,Roll,Name,Math,Physics,English,Total Marks,Grade,First name
0,1,Alice Johnson,85,78.0,92.0,255.0,A,Alice
1,2,Bob Smith,72,88.0,65.0,225.0,A,Bob
2,3,Carol White,90,95.0,NaN,NaN,A,Carol
3,4,David Brown,55,60.0,70.0,185.0,A,David
4,5,Emma Davis,78,82.0,85.0,245.0,A,Emma
5,6,Frank Miller,63,57.0,74.0,194.0,A,Frank
6,7,Grace Wilson,91,89.0,93.0,273.0,A+,Grace
7,8,Henry Moore,48,52.0,61.0,161.0,A,Henry
8,9,Isabella Taylor,76,79.0,NaN,NaN,A,Isabella
9,10,James Anderson,83,75.0,87.0,245.0,A,James
10,11,Karen Thomas,69,71.0,68.0,208.0,A,Karen
11,12,Liam Jackson,95,92.0,90.0,277.0,A+,Liam
12,13,Mia Harris,57,63.0,72.0,192.0,A,Mia
13,14,Noah Martin,80,77.0,83.0,240.0,A,Noah
14,15,Olivia Garcia,85,78.0,NaN,NaN,A,Olivia
15,16,Paul Martinez,61,66.0,59.0,186.0,A,Paul
16,17,Quinn Robinson,88,91.0,86.0,265.0,A,Quinn
17,18,Rachel Clark,53,49.0,64.0,166.0,A,Rachel
18,19,Samuel Rodriguez,77,NaN,80.0,NaN,A,Samuel
19,20,Tina Lewis,92,88.0,94.0,274.0,A+,Tina

In [19]:
# changes in df only not in the file 
df.to_csv("new_students_marks.csv")

Checking Duplicate ans null

In [26]:
Df

     name      city  salary
10  Alice  New York   85000
20    Bob  New York   77000
30  Carol   Houston   91000
40  David   Seattle   72000
50    Bob  New York   77000

In [28]:
# works on column /series 
Df["name"].unique()

array(['Alice', 'Bob', 'Carol', 'David'], dtype=object)

In [ ]:
df

In [31]:
len(df['Math'].unique()) #
df['Math'].nunique() # number of unique value in math column

19

In [32]:
df.nunique()

Roll           20
Name           20
Math           19
Physics        17
English        17
Total Marks    15
Grade           2
First name     20
dtype: int64

In [ ]:
df.isnull()
df["English"].isnull()
df["English"].notnull()

In [37]:
df["English"].isnull().sum() 
df["Math"].hasnans # check if there is any null value in math column

False

Duplicate values

In [39]:
Df

     name      city  salary
10  Alice  New York   85000
20    Bob  New York   77000
30  Carol   Houston   91000
40  David   Seattle   72000
50    Bob  New York   77000

In [41]:
Df.duplicated().sum() # count the number of duplicate rows
Df.drop_duplicates()

     name      city  salary
10  Alice  New York   85000
20    Bob  New York   77000
30  Carol   Houston   91000
40  David   Seattle   72000

In [42]:
Df.drop_duplicates(inplace=True) # permanet delete

In [45]:
Df.drop_duplicates(subset=["name"]) # deleet based on name

     name      city  salary
10  Alice  New York   85000
20    Bob  New York   77000
30  Carol   Houston   91000
40  David   Seattle   72000

In [47]:
Df.drop_duplicates(subset=["city"] , keep='last') # keep the last one

     name      city  salary
10  Alice  New York   85000
30  Carol   Houston   91000
40  David   Seattle   72000

In [48]:
df

,Roll,Name,Math,Physics,English,Total Marks,Grade,First name
0,1,Alice Johnson,85,78.0,92.0,255.0,A,Alice
1,2,Bob Smith,72,88.0,65.0,225.0,A,Bob
2,3,Carol White,90,95.0,NaN,NaN,A,Carol
3,4,David Brown,55,60.0,70.0,185.0,A,David
4,5,Emma Davis,78,82.0,85.0,245.0,A,Emma
5,6,Frank Miller,63,57.0,74.0,194.0,A,Frank
6,7,Grace Wilson,91,89.0,93.0,273.0,A+,Grace
7,8,Henry Moore,48,52.0,61.0,161.0,A,Henry
8,9,Isabella Taylor,76,79.0,NaN,NaN,A,Isabella
9,10,James Anderson,83,75.0,87.0,245.0,A,James
10,11,Karen Thomas,69,71.0,68.0,208.0,A,Karen
11,12,Liam Jackson,95,92.0,90.0,277.0,A+,Liam
12,13,Mia Harris,57,63.0,72.0,192.0,A,Mia
13,14,Noah Martin,80,77.0,83.0,240.0,A,Noah
14,15,Olivia Garcia,85,78.0,NaN,NaN,A,Olivia
15,16,Paul Martinez,61,66.0,59.0,186.0,A,Paul
16,17,Quinn Robinson,88,91.0,86.0,265.0,A,Quinn
17,18,Rachel Clark,53,49.0,64.0,166.0,A,Rachel
18,19,Samuel Rodriguez,77,NaN,80.0,NaN,A,Samuel
19,20,Tina Lewis,92,88.0,94.0,274.0,A+,Tina

In [ ]:
df.dropna() # drop all rows with any null value

In [ ]:
df.dropna(how="all" , inplace=True) # drop rows where all values are null

In [70]:
df.dropna(subset=["Physics"] , inplace=True) # drop rows where physics is null

In [ ]:
df.fillna(0)

In [61]:
df["Name"].fillna("Unknown" , inplace=True)
df

    Roll              Name  Math  Physics  English
0      1     Alice Johnson    85     78.0     92.0
1      2         Bob Smith    72     88.0     65.0
2      3       Carol White    90     95.0      NaN
3      4       David Brown    55     60.0     70.0
4      5        Emma Davis    78     82.0     85.0
5      6      Frank Miller    63     57.0     74.0
6      7      Grace Wilson    91     89.0     93.0
7      8       Henry Moore    48     52.0     61.0
8      9   Isabella Taylor    76     79.0      NaN
9     10    James Anderson    83     75.0     87.0
10    11      Karen Thomas    69     71.0     68.0
11    12      Liam Jackson    95     92.0     90.0
12    13        Mia Harris    57     63.0     72.0
13    14       Noah Martin    80     77.0     83.0
14    15     Olivia Garcia    85     78.0      NaN
15    16     Paul Martinez    61     66.0     59.0
16    17    Quinn Robinson    88     91.0     86.0
17    18      Rachel Clark    53     49.0     64.0
18    19  Samuel Rodriguez    77      NaN     80.0
19    20           Unknown    92     88.0     94.0

In [62]:
df["Physics"].fillna(df["Physics"].mean())

0     78.000000
1     88.000000
2     95.000000
3     60.000000
4     82.000000
5     57.000000
6     89.000000
7     52.000000
8     79.000000
9     75.000000
10    71.000000
11    92.000000
12    63.000000
13    77.000000
14    78.000000
15    66.000000
16    91.000000
17    49.000000
18    75.263158
19    88.000000
Name: Physics, dtype: float64

Staistical functionals

In [63]:
print(df["Math"].sum())
print(df["Math"].min())
print(df["Math"].max())
print(df["Math"].mean())
print(df["Math"].std())  # bichuti
print(df["Math"].median()) # moddhok 
print(df["Math"].mode()) # frequency
print(df[["Math" , "English"]].corr())

# sum of two different column row wise 
df[["Math", "English"]].sum(axis=1)

1498
48
95
74.9
14.443720179772901
77.5
0    85
Name: Math, dtype: int64
             Math   English
Math     1.000000  0.896021
English  0.896021  1.000000

In [78]:
# sum of two different column row wise 
df[["Math", "English"]].sum(axis=1)

0     177.0
1     137.0
2      90.0
3     125.0
4     163.0
5     137.0
6     184.0
7     109.0
8      76.0
9     170.0
10    137.0
11    185.0
12    129.0
13    163.0
14     85.0
15    120.0
16    174.0
17    117.0
18    157.0
19    186.0
dtype: float64

In [81]:

df["Total mark"] = df.iloc[:: , 2:5].sum(axis=1) # :: -> all row , 2:5 -> 2,3,4 (math, english, physics) , axis =1 -> row wise sum
df

    Roll              Name  Math  Physics  English  Total mark
0      1     Alice Johnson    85       78     92.0       255.0
1      2         Bob Smith    72       88     65.0       225.0
2      3       Carol White    90       95      NaN       185.0
3      4       David Brown    55       60     70.0       185.0
4      5        Emma Davis    78       82     85.0       245.0
5      6      Frank Miller    63       57     74.0       194.0
6      7      Grace Wilson    91       89     93.0       273.0
7      8       Henry Moore    48       52     61.0       161.0
8      9   Isabella Taylor    76       79      NaN       155.0
9     10    James Anderson    83       75     87.0       245.0
10    11      Karen Thomas    69       71     68.0       208.0
11    12      Liam Jackson    95       92     90.0       277.0
12    13        Mia Harris    57       63     72.0       192.0
13    14       Noah Martin    80       77     83.0       240.0
14    15     Olivia Garcia    85       78      NaN       163.0
15    16     Paul Martinez    61       66     59.0       186.0
16    17    Quinn Robinson    88       91     86.0       265.0
17    18      Rachel Clark    53       49     64.0       166.0
18    19  Samuel Rodriguez    77       78     80.0       235.0
19    20               NaN    92       88     94.0       274.0

In [82]:
df.describe()

           Roll      Math    Physics    English  Total mark
count  20.00000  20.00000  20.000000  17.000000   20.000000
mean   10.50000  74.90000  75.400000  77.823529  216.450000
std     5.91608  14.44372  13.701325  11.922853   41.645718
min     1.00000  48.00000  49.000000  59.000000  155.000000
25%     5.75000  62.50000  65.250000  68.000000  185.000000
50%    10.50000  77.50000  78.000000  80.000000  216.500000
75%    15.25000  85.75000  88.000000  87.000000  247.500000
max    20.00000  95.00000  95.000000  94.000000  277.000000

Apply function on df

In [85]:
# apply is used to apply a function to each element of a column or row in a DataFrame.

import pandas as pd
import numpy as np

df1 = pd.DataFrame({
    'Math':    [85, 92, 78, 90],
    'Science': [88, 79, 95, 83],
    'English': [72, 85, 80, 91]
}, index=['Alice', 'Bob', 'Charlie', 'David'])

print(df1)

# Apply along columns (axis=0) — stats per subject
print(df1.apply(np.mean, axis=0))

# Apply along rows (axis=1) — stats per student
df1['Average'] = df1.apply(np.mean, axis=1)
df1['Grade']   = df1['Average'].apply(lambda x: 'A' if x >= 85 else 'B')

print(df1)

         Math  Science  English
Alice      85       88       72
Bob        92       79       85
Charlie    78       95       80
David      90       83       91
Math       86.25
Science    86.25
English    82.00
dtype: float64
         Math  Science  English    Average Grade
Alice      85       88       72  81.666667     B
Bob        92       79       85  85.333333     A
Charlie    78       95       80  84.333333     B
David      90       83       91  88.000000     A

In [ ]:
df

In [12]:

df["Total Marks"] = df["Math"] + df["English"] + df["Physics"]
df

    Roll              Name  Math  Physics  English Section  Total Marks
0      1     Alice Johnson    85       78     92.0       A        255.0
1      2         Bob Smith    72       88     65.0       B        225.0
2      3       Carol White    90       95      NaN       B          NaN
3      4       David Brown    55       60     70.0       A        185.0
4      5        Emma Davis    78       82     85.0       B        245.0
5      6      Frank Miller    63       57     74.0       A        194.0
6      7      Grace Wilson    91       89     93.0       B        273.0
7      8       Henry Moore    48       52     61.0       A        161.0
8      9   Isabella Taylor    76       79      NaN       B          NaN
9     10    James Anderson    83       75     87.0       A        245.0
10    11      Karen Thomas    69       71     68.0       B        208.0
11    12      Liam Jackson    95       92     90.0       A        277.0
12    13        Mia Harris    57       63     72.0       B        192.0
13    14       Noah Martin    80       77     83.0       A        240.0
14    15     Olivia Garcia    85       78      NaN       B          NaN
15    16     Paul Martinez    61       66     59.0       A        186.0
16    17    Quinn Robinson    88       91     86.0       B        265.0
17    18      Rachel Clark    53       49     64.0       A        166.0
18    19  Samuel Rodriguez    77       78     80.0       B        235.0
19    20               NaN    92       88     94.0       A        274.0

In [93]:
mn=df["Total Marks"].min()
max=df["Total Marks"].max()

df["Scaled Marks"]=df["Total Marks"].apply(lambda x : (x-mn)/(max-mn))
df

    Roll              Name  Math  Physics  English  Total Marks  Scaled Marks
0      1     Alice Johnson    85       78     92.0        255.0      0.810345
1      2         Bob Smith    72       88     65.0        225.0      0.551724
2      3       Carol White    90       95      NaN          NaN           NaN
3      4       David Brown    55       60     70.0        185.0      0.206897
4      5        Emma Davis    78       82     85.0        245.0      0.724138
5      6      Frank Miller    63       57     74.0        194.0      0.284483
6      7      Grace Wilson    91       89     93.0        273.0      0.965517
7      8       Henry Moore    48       52     61.0        161.0      0.000000
8      9   Isabella Taylor    76       79      NaN          NaN           NaN
9     10    James Anderson    83       75     87.0        245.0      0.724138
10    11      Karen Thomas    69       71     68.0        208.0      0.405172
11    12      Liam Jackson    95       92     90.0        277.0      1.000000
12    13        Mia Harris    57       63     72.0        192.0      0.267241
13    14       Noah Martin    80       77     83.0        240.0      0.681034
14    15     Olivia Garcia    85       78      NaN          NaN           NaN
15    16     Paul Martinez    61       66     59.0        186.0      0.215517
16    17    Quinn Robinson    88       91     86.0        265.0      0.896552
17    18      Rachel Clark    53       49     64.0        166.0      0.043103
18    19  Samuel Rodriguez    77       78     80.0        235.0      0.637931
19    20               NaN    92       88     94.0        274.0      0.974138

In [ ]:
# custom function 

def grade(marks) :
    if marks >= 270 :
        return "A+"
    elif marks >= 240 :
        return "A"
    elif marks >= 210 :
        return "B"
    else :
        return "C"

df["Grade"] = df["Total Marks"].apply(grade)  ## column wise 
df

,Roll,Name,Math,Physics,English,Total Marks,Scaled Marks,Grade
0,1,Alice Johnson,85,78,92.0,255.0,0.810345,A
1,2,Bob Smith,72,88,65.0,225.0,0.551724,B
2,3,Carol White,90,95,NaN,NaN,NaN,C
3,4,David Brown,55,60,70.0,185.0,0.206897,C
4,5,Emma Davis,78,82,85.0,245.0,0.724138,A
5,6,Frank Miller,63,57,74.0,194.0,0.284483,C
6,7,Grace Wilson,91,89,93.0,273.0,0.965517,A+
7,8,Henry Moore,48,52,61.0,161.0,0.000000,C
8,9,Isabella Taylor,76,79,NaN,NaN,NaN,C
9,10,James Anderson,83,75,87.0,245.0,0.724138,A
10,11,Karen Thomas,69,71,68.0,208.0,0.405172,C
11,12,Liam Jackson,95,92,90.0,277.0,1.000000,A+
12,13,Mia Harris,57,63,72.0,192.0,0.267241,C
13,14,Noah Martin,80,77,83.0,240.0,0.681034,A
14,15,Olivia Garcia,85,78,NaN,NaN,NaN,C
15,16,Paul Martinez,61,66,59.0,186.0,0.215517,C
16,17,Quinn Robinson,88,91,86.0,265.0,0.896552,A
17,18,Rachel Clark,53,49,64.0,166.0,0.043103,C
18,19,Samuel Rodriguez,77,78,80.0,235.0,0.637931,B
19,20,NaN,92,88,94.0,274.0,0.974138,A+

In [97]:
def making_system(df) :
    a = df["Math"]+2
    b= df["English"]+2
    c= df["Physics"]+2
    return a+b+c

df["Raised Total Mark"] =df.apply(making_system , axis=1 ) # row wise 
df

    Roll              Name  Math  Physics  English Section  Raised Total Mark
0      1     Alice Johnson    85       78     92.0       A              261.0
1      2         Bob Smith    72       88     65.0       B              231.0
2      3       Carol White    90       95      NaN       B                NaN
3      4       David Brown    55       60     70.0       A              191.0
4      5        Emma Davis    78       82     85.0       B              251.0
5      6      Frank Miller    63       57     74.0       A              200.0
6      7      Grace Wilson    91       89     93.0       B              279.0
7      8       Henry Moore    48       52     61.0       A              167.0
8      9   Isabella Taylor    76       79      NaN       B                NaN
9     10    James Anderson    83       75     87.0       A              251.0
10    11      Karen Thomas    69       71     68.0       B              214.0
11    12      Liam Jackson    95       92     90.0       A              283.0
12    13        Mia Harris    57       63     72.0       B              198.0
13    14       Noah Martin    80       77     83.0       A              246.0
14    15     Olivia Garcia    85       78      NaN       B                NaN
15    16     Paul Martinez    61       66     59.0       A              192.0
16    17    Quinn Robinson    88       91     86.0       B              271.0
17    18      Rachel Clark    53       49     64.0       A              172.0
18    19  Samuel Rodriguez    77       78     80.0       B              241.0
19    20               NaN    92       88     94.0       A              280.0

Date and Time

In [ ]:
# for more example visit : https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html

Groupby

In [4]:
grouped = df.groupby('Section') # group by section column
grouped

In [13]:
for Section , info in grouped :
    print("Section: ", Section)
    display(info)  # info is the dataframe

Section:  A

    Roll            Name  Math  Physics  English Section  Total Marks
0      1   Alice Johnson    85       78     92.0       A        255.0
3      4     David Brown    55       60     70.0       A        185.0
5      6    Frank Miller    63       57     74.0       A        194.0
7      8     Henry Moore    48       52     61.0       A        161.0
9     10  James Anderson    83       75     87.0       A        245.0
11    12    Liam Jackson    95       92     90.0       A        277.0
13    14     Noah Martin    80       77     83.0       A        240.0
15    16   Paul Martinez    61       66     59.0       A        186.0
17    18    Rachel Clark    53       49     64.0       A        166.0
19    20             NaN    92       88     94.0       A        274.0

Section:  B

    Roll              Name  Math  Physics  English Section  Total Marks
1      2         Bob Smith    72       88     65.0       B        225.0
2      3       Carol White    90       95      NaN       B          NaN
4      5        Emma Davis    78       82     85.0       B        245.0
6      7      Grace Wilson    91       89     93.0       B        273.0
8      9   Isabella Taylor    76       79      NaN       B          NaN
10    11      Karen Thomas    69       71     68.0       B        208.0
12    13        Mia Harris    57       63     72.0       B        192.0
14    15     Olivia Garcia    85       78      NaN       B          NaN
16    17    Quinn Robinson    88       91     86.0       B        265.0
18    19  Samuel Rodriguez    77       78     80.0       B        235.0

In [9]:
grouped.min(numeric_only=True)

         Roll  Math  Physics  English
Section
A           1    48       49     59.0
B           2    57       63     65.0

In [14]:
grouped.describe()

         Roll                                              Math        ...  \
        count  mean       std  min  25%   50%   75%   max count  mean  ...
Section                                                                ...
A        10.0  10.9  6.226288  1.0  6.5  11.0  15.5  20.0  10.0  71.5  ...
B        10.0  10.1  5.896327  2.0  5.5  10.0  14.5  19.0  10.0  78.3  ...

        Physics       English                                                 \
            75%   max   count       mean        std   min   25%   50%    75%
Section
A         77.75  92.0    10.0  77.400000  13.434615  59.0  65.5  78.5  89.25
B         88.75  95.0     7.0  78.428571  10.373960  65.0  70.0  80.0  85.50


          max
Section
A        94.0
B        93.0

[2 rows x 32 columns]

In [16]:
mean_marks= grouped["Total Marks"].mean() # mean of total marks for each section
mean_marks

Section
A    218.300000
B    234.714286
Name: Total Marks, dtype: float64

In [17]:
#fiiling the null marks with mean of total marks for each section
df["Total Marks"] =df["Total Marks"].fillna(df["Section"].map(mean_marks)) #
df

    Roll              Name  Math  Physics  English Section  Total Marks
0      1     Alice Johnson    85       78     92.0       A   255.000000
1      2         Bob Smith    72       88     65.0       B   225.000000
2      3       Carol White    90       95      NaN       B   234.714286
3      4       David Brown    55       60     70.0       A   185.000000
4      5        Emma Davis    78       82     85.0       B   245.000000
5      6      Frank Miller    63       57     74.0       A   194.000000
6      7      Grace Wilson    91       89     93.0       B   273.000000
7      8       Henry Moore    48       52     61.0       A   161.000000
8      9   Isabella Taylor    76       79      NaN       B   234.714286
9     10    James Anderson    83       75     87.0       A   245.000000
10    11      Karen Thomas    69       71     68.0       B   208.000000
11    12      Liam Jackson    95       92     90.0       A   277.000000
12    13        Mia Harris    57       63     72.0       B   192.000000
13    14       Noah Martin    80       77     83.0       A   240.000000
14    15     Olivia Garcia    85       78      NaN       B   234.714286
15    16     Paul Martinez    61       66     59.0       A   186.000000
16    17    Quinn Robinson    88       91     86.0       B   265.000000
17    18      Rachel Clark    53       49     64.0       A   166.000000
18    19  Samuel Rodriguez    77       78     80.0       B   235.000000
19    20               NaN    92       88     94.0       A   274.000000