In [7]:
# pandas -> data cleaning , data manipulation, data analysis
import pandas as pd

data = pd.read_csv('./students_marks.csv')
data

    Roll              Name  Math  Physics  English
0      1     Alice Johnson    85       78       92
1      2         Bob Smith    72       88       65
2      3       Carol White    90       95       88
3      4       David Brown    55       60       70
4      5        Emma Davis    78       82       85
5      6      Frank Miller    63       57       74
6      7      Grace Wilson    91       89       93
7      8       Henry Moore    48       52       61
8      9   Isabella Taylor    76       80       79
9     10    James Anderson    83       75       87
10    11      Karen Thomas    69       71       68
11    12      Liam Jackson    95       92       90
12    13        Mia Harris    57       63       72
13    14       Noah Martin    80       77       83
14    15     Olivia Garcia    74       85       78
15    16     Paul Martinez    61       66       59
16    17    Quinn Robinson    88       91       86
17    18      Rachel Clark    53       49       64
18    19  Samuel Rodriguez    77       73       80
19    20        Tina Lewis    92       88       94

In [ ]:
#dataFrame and series 

print(type(data)) # dataFrame
#DataFrame -> 2D data structure -> rows and columns , table

name = data['Name']
#print(name)
print(type(name)) # Series -> 1D data structure , coloum /row

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

Basic pandas functioalities

In [ ]:
data.head(3) # first 3 rows
data.tail() # last 5 rows
data.sample(5) # random 5 rows

    Roll              Name  Math  Physics  English
15    16     Paul Martinez    61       66       59
16    17    Quinn Robinson    88       91       86
17    18      Rachel Clark    53       49       64
18    19  Samuel Rodriguez    77       73       80
19    20        Tina Lewis    92       88       94

In [16]:
print(data.columns)
import numpy as np
col = np.array(data.columns)
print(col)
print(col.dtype)

Index(['Roll', 'Name', 'Math', 'Physics', 'English'], dtype='str')
['Roll' 'Name' 'Math' 'Physics' 'English']
object

In [18]:
data.index
list =np.array(data.index)
print(list)
print(list.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [19]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Roll     20 non-null     int64
 1   Name     20 non-null     str
 2   Math     20 non-null     int64
 3   Physics  20 non-null     int64
 4   English  20 non-null     int64
dtypes: int64(4), str(1)
memory usage: 1.1 KB

In [ ]:
data.describe() # numberical columns

           Roll       Math    Physics   English
count  20.00000  20.000000  20.000000  20.00000
mean   10.50000  74.350000  75.550000  78.40000
std     5.91608  14.246976  13.877187  11.17516
min     1.00000  48.000000  49.000000  59.00000
25%     5.75000  62.500000  65.250000  69.50000
50%    10.50000  76.500000  77.500000  79.50000
75%    15.25000  85.750000  88.000000  87.25000
max    20.00000  95.000000  95.000000  94.00000

DataFrame from Inbuilt

In [ ]:
# list to dataFrame
mylist = [['Alice' , 85] ,
          ['Bob' , 90] ,
          ['Charlie' , 78 ]]  # 2D list 

list_dataFrame= pd.DataFrame(mylist , columns=['name' , 'marks']) # list to dataFrame
print(list_dataFrame)

      name  marks
0    Alice     85
1      Bob     90
2  Charlie     78

In [23]:
#tuple to dataFrame
mytuple= (('Alice' , 56) ,
          ('Bob' , 70) ,
          ('charlie' , 80)) # 2D tuple

tuple_dataFrame = pd.DataFrame(mytuple , columns=['name' , 'marks']) 
print(tuple_dataFrame)

      name  marks
0    Alice     56
1      Bob     70
2  charlie     80

In [24]:
# dictionary to dataFrame

mydictionary= {
    'name' : ['Alice'   , 'Bob' , 'Charlie'] ,
    'marks' : [56 , 70 , 80]}

dict_dataFrame = pd.DataFrame(mydictionary)
print(dict_dataFrame)

      name  marks
0    Alice     56
1      Bob     70
2  Charlie     80

In [26]:
mydata = [
    {'name' : 'Alice' , 'marks' : 85} ,
    {'name' : 'Bob' , 'marks' : 90} ,
    {'name' : 'Charlie' }
]   # list of dictionary

dataFrame_from_list_of_dict = pd.DataFrame(mydata)
print(dataFrame_from_list_of_dict)

      name  marks
0    Alice   85.0
1      Bob   90.0
2  Charlie    NaN

Data Accessing

In [27]:
data

    Roll              Name  Math  Physics  English
0      1     Alice Johnson    85       78       92
1      2         Bob Smith    72       88       65
2      3       Carol White    90       95       88
3      4       David Brown    55       60       70
4      5        Emma Davis    78       82       85
5      6      Frank Miller    63       57       74
6      7      Grace Wilson    91       89       93
7      8       Henry Moore    48       52       61
8      9   Isabella Taylor    76       80       79
9     10    James Anderson    83       75       87
10    11      Karen Thomas    69       71       68
11    12      Liam Jackson    95       92       90
12    13        Mia Harris    57       63       72
13    14       Noah Martin    80       77       83
14    15     Olivia Garcia    74       85       78
15    16     Paul Martinez    61       66       59
16    17    Quinn Robinson    88       91       86
17    18      Rachel Clark    53       49       64
18    19  Samuel Rodriguez    77       73       80
19    20        Tina Lewis    92       88       94

In [ ]:
# data['Math']   # accessing column

#loc[row(index) , column (features)]
# loc[row start : row end , col start : col end ]

data.loc[0] # accessing first row
type(data.loc[0]) # -> Series

pandas.Series

In [ ]:
#multiple row via list

data.loc[[2,3,15]]

   Roll          Name  Math  Physics  English
4     5    Emma Davis    78       82       85
5     6  Frank Miller    63       57       74
6     7  Grace Wilson    91       89       93
7     8   Henry Moore    48       52       61

In [38]:
data.loc[4:7] # accessing rows from index 4 to 7

   Roll          Name  Math  Physics  English
4     5    Emma Davis    78       82       85
5     6  Frank Miller    63       57       74
6     7  Grace Wilson    91       89       93
7     8   Henry Moore    48       52       61

In [41]:
data.loc[: , "Physics"] # accessing all rows of physics column

data.loc[: , ["Physics" , "Math"]] 

type(data.loc[: , ["Physics" , "Math"]] ) # -> DataFrame

pandas.DataFrame

In [42]:
data.loc[3:5 , ["Name" , "English"]]

           Name  English
3   David Brown       70
4    Emma Davis       85
5  Frank Miller       74

Changing index and column and iloc

In [54]:
data2= data.set_index('English') # changing index to 
print(data2)
#data2.loc[2:5] # error because index is changed to english and 2,3,4,5 are not present in english column

data2.iloc[2:5 , 0:3]

         Roll              Name  Math  Physics
English
92          1     Alice Johnson    85       78
65          2         Bob Smith    72       88
88          3       Carol White    90       95
70          4       David Brown    55       60
85          5        Emma Davis    78       82
74          6      Frank Miller    63       57
93          7      Grace Wilson    91       89
61          8       Henry Moore    48       52
79          9   Isabella Taylor    76       80
87         10    James Anderson    83       75
68         11      Karen Thomas    69       71
90         12      Liam Jackson    95       92
72         13        Mia Harris    57       63
83         14       Noah Martin    80       77
78         15     Olivia Garcia    74       85
59         16     Paul Martinez    61       66
86         17    Quinn Robinson    88       91
64         18      Rachel Clark    53       49
80         19  Samuel Rodriguez    77       73
94         20        Tina Lewis    92       88

         Roll         Name  Math
English
88          3  Carol White    90
70          4  David Brown    55
85          5   Emma Davis    78

In [59]:
data2.rename(columns ={"Roll" : "Student Roll"} , inplace =True)
print(data2.columns)

Index(['Student Roll', 'Name', 'Math', 'Physics'], dtype='str')

#dataFrame manupulation

In [ ]:

data.drop(0 , inplace =True)
print(data)

#data.drop(columns="Math" , inplace =true)

    Roll              Name  Math  Physics  English
1      2         Bob Smith    72       88       65
2      3       Carol White    90       95       88
3      4       David Brown    55       60       70
4      5        Emma Davis    78       82       85
5      6      Frank Miller    63       57       74
6      7      Grace Wilson    91       89       93
7      8       Henry Moore    48       52       61
8      9   Isabella Taylor    76       80       79
9     10    James Anderson    83       75       87
10    11      Karen Thomas    69       71       68
11    12      Liam Jackson    95       92       90
12    13        Mia Harris    57       63       72
13    14       Noah Martin    80       77       83
14    15     Olivia Garcia    74       85       78
15    16     Paul Martinez    61       66       59
16    17    Quinn Robinson    88       91       86
17    18      Rachel Clark    53       49       64
18    19  Samuel Rodriguez    77       73       80
19    20        Tina Lewis    92       88       94

In [ ]:
data.loc[1 , 'Math'] =94 # row 1 culum = math 
data.head(5)

   Roll          Name  Math  Physics  English
1     2     Bob Smith    94       88       65
2     3   Carol White    90       95       88
3     4   David Brown    55       60       70
4     5    Emma Davis    78       82       85
5     6  Frank Miller    63       57       74

In [66]:
data.loc[1:3 , 'Physics'] += 2
data.head(5)

   Roll          Name  Math  Physics  English
1     2     Bob Smith    94       90       65
2     3   Carol White    90       97       88
3     4   David Brown    55       62       70
4     5    Emma Davis    78       82       85
5     6  Frank Miller    63       57       74

In [68]:

for i , series in data.iterrows() :
    print (f"{i} : {series}")

1 : Roll               2
Name       Bob Smith
Math              94
Physics           90
English           65
Name: 1, dtype: object
2 : Roll                 3
Name       Carol White
Math                90
Physics             97
English             88
Name: 2, dtype: object
3 : Roll                 4
Name       David Brown
Math                55
Physics             62
English             70
Name: 3, dtype: object
4 : Roll                5
Name       Emma Davis
Math               78
Physics            82
English            85
Name: 4, dtype: object
5 : Roll                  6
Name       Frank Miller
Math                 63
Physics              57
English              74
Name: 5, dtype: object
6 : Roll                  7
Name       Grace Wilson
Math                 91
Physics              89
English              93
Name: 6, dtype: object
7 : Roll                 8
Name       Henry Moore
Math                48
Physics             52
English             61
Name: 7, dtype: object
8 : Roll                     9
Name       Isabella Taylor
Math                    76
Physics                 80
English                 79
Name: 8, dtype: object
9 : Roll                   10
Name       James Anderson
Math                   83
Physics                75
English                87
Name: 9, dtype: object
10 : Roll                 11
Name       Karen Thomas
Math                 69
Physics              71
English              68
Name: 10, dtype: object
11 : Roll                 12
Name       Liam Jackson
Math                 95
Physics              92
English              90
Name: 11, dtype: object
12 : Roll               13
Name       Mia Harris
Math               57
Physics            63
English            72
Name: 12, dtype: object
13 : Roll                14
Name       Noah Martin
Math                80
Physics             77
English             83
Name: 13, dtype: object
14 : Roll                  15
Name       Olivia Garcia
Math                  74
Physics               85
English               78
Name: 14, dtype: object
15 : Roll                  16
Name       Paul Martinez
Math                  61
Physics               66
English               59
Name: 15, dtype: object
16 : Roll                   17
Name       Quinn Robinson
Math                   88
Physics                91
English                86
Name: 16, dtype: object
17 : Roll                 18
Name       Rachel Clark
Math                 53
Physics              49
English              64
Name: 17, dtype: object
18 : Roll                     19
Name       Samuel Rodriguez
Math                     77
Physics                  73
English                  80
Name: 18, dtype: object
19 : Roll               20
Name       Tina Lewis
Math               92
Physics            88
English            94
Name: 19, dtype: object

In [70]:
for i in data.itertuples() :
    print(i)

Pandas(Index=1, Roll=2, Name='Bob Smith', Math=94, Physics=90, English=65)
Pandas(Index=2, Roll=3, Name='Carol White', Math=90, Physics=97, English=88)
Pandas(Index=3, Roll=4, Name='David Brown', Math=55, Physics=62, English=70)
Pandas(Index=4, Roll=5, Name='Emma Davis', Math=78, Physics=82, English=85)
Pandas(Index=5, Roll=6, Name='Frank Miller', Math=63, Physics=57, English=74)
Pandas(Index=6, Roll=7, Name='Grace Wilson', Math=91, Physics=89, English=93)
Pandas(Index=7, Roll=8, Name='Henry Moore', Math=48, Physics=52, English=61)
Pandas(Index=8, Roll=9, Name='Isabella Taylor', Math=76, Physics=80, English=79)
Pandas(Index=9, Roll=10, Name='James Anderson', Math=83, Physics=75, English=87)
Pandas(Index=10, Roll=11, Name='Karen Thomas', Math=69, Physics=71, English=68)
Pandas(Index=11, Roll=12, Name='Liam Jackson', Math=95, Physics=92, English=90)
Pandas(Index=12, Roll=13, Name='Mia Harris', Math=57, Physics=63, English=72)
Pandas(Index=13, Roll=14, Name='Noah Martin', Math=80, Physics=77, English=83)
Pandas(Index=14, Roll=15, Name='Olivia Garcia', Math=74, Physics=85, English=78)
Pandas(Index=15, Roll=16, Name='Paul Martinez', Math=61, Physics=66, English=59)
Pandas(Index=16, Roll=17, Name='Quinn Robinson', Math=88, Physics=91, English=86)
Pandas(Index=17, Roll=18, Name='Rachel Clark', Math=53, Physics=49, English=64)
Pandas(Index=18, Roll=19, Name='Samuel Rodriguez', Math=77, Physics=73, English=80)
Pandas(Index=19, Roll=20, Name='Tina Lewis', Math=92, Physics=88, English=94)

In [79]:
# sorting 
data
copy =data.sort_values(["Math" ,"Physics" ] , ascending =[0,1]) # sort by math in descending order and physics in ascending order
#data.sort_values("Math" , inplace = True)
copy

    Roll              Name  Math  Physics  English
11    12      Liam Jackson    95       92       90
1      2         Bob Smith    94       90       65
19    20        Tina Lewis    92       88       94
6      7      Grace Wilson    91       89       93
2      3       Carol White    90       97       88
16    17    Quinn Robinson    88       91       86
9     10    James Anderson    83       75       87
13    14       Noah Martin    80       77       83
4      5        Emma Davis    78       82       85
18    19  Samuel Rodriguez    77       73       80
8      9   Isabella Taylor    76       80       79
14    15     Olivia Garcia    74       85       78
10    11      Karen Thomas    69       71       68
5      6      Frank Miller    63       57       74
15    16     Paul Martinez    61       66       59
12    13        Mia Harris    57       63       72
3      4       David Brown    55       62       70
17    18      Rachel Clark    53       49       64
7      8       Henry Moore    48       52       61

In [81]:
# filtering data 
output = data.loc[data["Math"]==78]
output 

output2 = data.loc[(data["Math"] > 80) & (data["Physics"]<90)]
output2

    Roll            Name  Math  Physics  English
6      7    Grace Wilson    91       89       93
9     10  James Anderson    83       75       87
19    20      Tina Lewis    92       88       94